### PR TITLE
add json output to withings2, improve json format in sync and capture…

### PR DESCRIPTION
**Pull request by rob-miller**
Try again improving json format and capturing pulse and pulse wave velocity from Withings scale.
Working for json output and upload to Garmin in my testing.

### CODE REVIEW

**Comment by longstone** [comment]
@stynoo can you have a look here? Thanks!

**Comment by stynoo** [comment]
> @stynoo can you have a look here? Thanks!

Will do when I get back home (by the end of the month.)

**Comment by longstone** [comment]
Netter late than never 👍😉

**Comment by stv0g** [comment]
LGTM

**Pull request merged**
