### PR TITLE
Fix for the Cloudflare 403 error with http2 and the Garmin username is being parsed correctly again.

### PR DESCRIPTION
**Pull request by ciancim**
I fixed the CloudFlare 403 error by using HTTP/2. I replaced the cloudscraper library in garmin.py. This fix might work as well for the 401 error, but I could not test this as I only had 403 errors.

### CODE REVIEW

**Comment by cristian5th** [comment]
This update is solving the 403 issue for me too. Many thanks Manuel!

**Comment by ciancim** [comment]
I added a second commit to this pull-request, which also fixes the Garmin username which is not displaying anymore. This issue is being discussed here: https://github.com/jaroslawhartman/withings-sync/issues/47

**Comment by stynoo** [comment]
You just need to adjust the package list for install_requires in setup.py as well, otherwise lgtm!

**Comment by matthewnessworthy** [comment]
@jaroslawhartman would you mind merging and releasing if you're happy with the changes pelase?

**Comment by greykapp1001** [comment]
I previously had the 403 errors which looks like it is fixed with this amendment. Many thanks guys!

**Comment by wicol** [comment]
Resolves the issue and works good for me too. Please merge!

**Pull request merged**
