### PR TITLE
Multiple uploads of the same data

### PR DESCRIPTION
**Pull request by ossgeek314**
This patch should address issues of the same data being uploaded to Garmin if the sync is run multiple times per day as mentioned in issue #23 

It stores the timestamp of the last time the sync was run in the Withings user config file if no `--fromdate/-f` is provided on the command line.  

I've only done light testing, there might be edge cases not accounted for in the code.  

I'm not sure how Garmin/Withings deals with timezones, so there might need to be timezone shenanigan added as well.

### CODE REVIEW

**Comment by maha09-betssongroup** [comment]
I'm having trouble with duplicate entries being uploaded to Garmin, any chance of this being merged any time soon?

**Comment by mwhrtin** [comment]
I'm having trouble with duplicate entries being uploaded to Garmin, any chance of this being merged any time soon?

**Comment by embear** [comment]
I also would like to see this merged. But if I understand the patch correctly the `withings.setLastSync()` is called unconditionally from the result of the actual upload. If either Garmin or TrainerRoad upload fails it will never be tried again. In my opinion it should only be called if all requested upload destinations completed with no error.

**Comment by longstone** [comment]
> I also would like to see this merged. But if I understand the patch correctly the `withings.setLastSync()` is called unconditionally from the result of the actual upload. If either Garmin or TrainerRoad upload fails it will never be tried again. In my opinion it should only be called if all requested upload destinations completed with no error.

@embear I see the scenario, where sync failed but `lastSync` is written. In this case the state could manually be fixed, setting the `fromDate`. Also we would need to define what happen if TR was successsful and Garmin not. I think either persisting the last successful Sync **to** System instead of **from**?

Do you think we can take this risk and go forward?

**Comment by embear** [comment]
I think that persisting the information to which destination the upload was successful would be the right way, at least for my use case. It would be best to check if there is some destination that had not been updated and download data from withings only if this is the case.
I'm not sure if this should be changed before the merge.

**Comment by longstone** [comment]
I'm going to merge this. To implement the behaviour as desired for the case with both endpoints, I've opened a Issue: #61

**Pull request merged**
