### PR TITLE
Feature/enable blood pressure

### PR DESCRIPTION
**Pull request by longstone**
As mentioned in #106, blood pressure is enabled for US users.

This PR brings a feature flag option. And a feature flag'BLOOD_PRESSURE'. 
Enabling blood pressure should sync the retrieved value to Garmin.
Also, it contains some heavier refactoring.

Weight and Blood Pressure are written to different files and then uploaded to Garmin.

- feat: add function to write blood pressure to fit
- feat: write two different files (blood pressure and weight)
- feat: add handling of weight and blood pressure
- feat: add the argument to enable feature flags (--features)
- feat: add documentation
- feat: add feature flag BLOOD_PRESSURE
- refactor: create a class for weight and blood pressure
- chore: refactor writing fit data method

### CODE REVIEW

**Comment by longstone** [comment]
fyi @stynoo

**Comment by longstone** [comment]
I would be thankful for some testing and also a code review. As a non-native pythoner, this was quite a challenge.

Implementing and going through FIT-Documentation leads to high blood pressure 😢

**Comment by longstone** [comment]
**push**

Can anybody give feedback here? Following @alvins711 instruction, I was able to enable BP sync:

> You can enable the BP stats by changing your account's country to US from garmin.com (not connect.garmin.com).

Also testing without BP is welcome

/cc @stv0g @stynoo  @jaroslawhartman @alvins711

**Comment by stynoo** [comment]
Hi @longstone, my apologies for the delay.  

I can confirm that this is working, did one measurement with a Withings BPM connect and it synced Sys, Dia & bpm to a test account in US.  

That's quite a job you did here!  I was dreading the dive into the FIT file generation code....

**Comment by alvins711** [comment]
Hi @longstone, Just confirming the BP sync is working. Had several days worth of BP readings in Withings and it sync'ed to Garmin as well as Body composition measurements correctly.

**Comment by stynoo** [comment]
When syncing a measurement that doesn't contain weight nor blood pressure data (for example when using the withings thermometer) it errors like this:
```
File "/home/stynoo/.cache/pypoetry/virtualenvs/devenv-VH2C0X2b-py3.9/lib/python3.9/site-packages/withings_sync/sync.py", line 377, in groupdata_log_raw_data
    for dataentry in groupdata["raw_data"]:
KeyError: 'raw_data'
```

An easy fix is to populate group_data by default with the raw_data: 
```
    for group in groups:
        # Get extra physical measurements
        dt = group.get_datetime()
        group_data = {
            "date_time": group.get_datetime(),
            "type": "None",
            "raw_data": group.get_raw_data(),
        }
```

**Comment by longstone** [comment]
I changed this now. Thank you very much! I plan to merge this later.

**Pull request merged**
